# Generated by Django 5.2.5 on 2025-08-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0003_categoria_created_at_categoria_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10),
        ),
    ]
